### ISSUE TITLE
Ceres solver 2.2.0 delete cx_sparse

### ISSUE THREAD

**Issue by zhaozhongch** [openMVG/openMVG#2171]
ceres solver 2.2.0 has deleted the cx sparse option, which is used in the `sfm_steller_engine.cpp`. If compile with ceres solver 2.2.0, error occurs
```
/home/zhaozhong/tools/openMVG/src/openMVG/sfm/pipelines/stellar/sfm_stellar_engine.cpp:736:66: error: ‘CX_SPARSE’ is not a member of ‘ceres’; did you mean ‘NO_SPARSE’?
  736 |          ceres::IsSparseLinearAlgebraLibraryTypeAvailable(ceres::CX_SPARSE) ||
```

**Comment by pmoulon** [comment]
Thx for reporting. I will update the code soon as it is done in the other pipelines

**Comment by pmoulon** [comment]
Just pushed a fix, can you test it?

**Comment by zhaozhongch** [comment]
compile works fine. Thanks!
