### ISSUE TITLE
2.0 fails to compile with ceres-solver-2.2.0: no member named 'CX_SPARSE' in namespace 'ceres'

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#2255]
```
/wrkdirs/usr/ports/misc/openmvg/work/openMVG-2.0/src/openMVG/multiview/rotation_averaging_l2.cpp:287:68: error: no member named 'CX_SPARSE' in namespace 'ceres'; did you mean 'NO_SPARSE'?
  else if (ceres::IsSparseLinearAlgebraLibraryTypeAvailable(ceres::CX_SPARSE))
                                                            ~~~~~~~^~~~~~~~~
                                                                   NO_SPARSE
/usr/local/include/ceres/types.h:184:3: note: 'NO_SPARSE' declared here
  NO_SPARSE
  ^
/wrkdirs/usr/ports/misc/openmvg/work/openMVG-2.0/src/openMVG/multiview/rotation_averaging_l2.cpp:289:63: error: no member named 'CX_SPARSE' in namespace 'ceres'; did you mean 'NO_SPARSE'?
    solverOptions.sparse_linear_algebra_library_type = ceres::CX_SPARSE;
                                                       ~~~~~~~^~~~~~~~~
                                                              NO_SPARSE
/usr/local/include/ceres/types.h:184:3: note: 'NO_SPARSE' declared here
  NO_SPARSE
  ^
2 errors generated.
```

clang-16
FreeBSD 13.2

**Comment by pmoulon** [comment]
Thank you. Let's fix that and see if there is a way to be compatible with the old and new API.

**Comment by yurivict** [comment]
The latest revision doesn't have such problem.
Maybe you can just make a releasee?
