### ISSUE TITLE
Compiling error on Fedora 23

### ISSUE THREAD

**Issue by gnudo** [openMVG/openMVG#496]
Hi folks,

I wanted to try openMVG on a Fedora 23 system (on Mac OSX El Capitan it compiles fine for me), but I keep getting the following error:
```
/usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../lib64/liblapack.so: undefined reference to `_gfortran_transfer_character_write@GFORTRAN_1.4'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tried to compile with both gcc/g++ (5.3.1) and clang (3.7.), but it doesn't make any difference. Before further investigating, I was wondering whether someone had a similar experience or there already exists a strong argument of not using Fedora23 and/or the respective gcc/clang/lapack versions?

Thanks in advance for the help,
Goran

To reproduce the error, I run:
```
/usr/bin/clang++    -march=core-avx2 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-xop -mno-fma4 --std=c++11 -O3   CMakeFiles/openMVG_main_ComputeFeatures.dir/main_ComputeFeatures.cpp.o  -o ../../Linux-x86_64-Release/openMVG_main_ComputeFeatures -rdynamic ../../Linux-x86_64-Release/libopenMVG_image.so.0.8 ../../Linux-x86_64-Release/libopenMVG_features.so.0.8 ../../Linux-x86_64-Release/libopenMVG_sfm.so.0.8 ../../Linux-x86_64-Release/libstlplus.a ../../Linux-x86_64-Release/libvlsift.a /home/lovric_g/Applications/anaconda2/lib/libpng.so /home/lovric_g/Applications/anaconda2/lib/libz.so /home/lovric_g/Applications/anaconda2/lib/libjpeg.so /home/lovric_g/Applications/anaconda2/lib/libtiff.so ../../Linux-x86_64-Release/libopenMVG_system.so.0.8 ../../Linux-x86_64-Release/libopenMVG_multiview.so.0.8 ../../Linux-x86_64-Release/libopenMVG_numeric.so.0.8 ../../Linux-x86_64-Release/liblemon.a ../../lib/libceres.a -llapack -lblas ../../Linux-x86_64-Release/libcxsparse.a -lm ../../Linux-x86_64-Release/libopenMVG_lInftyComputerVision.so.0.8 ../../Linux-x86_64-Release/liblib_clp.a ../../Linux-x86_64-Release/liblib_OsiClpSolver.a ../../Linux-x86_64-Release/liblib_CoinUtils.a ../../Linux-x86_64-Release/liblib_Osi.a ../../Linux-x86_64-Release/libopenMVG_matching.so.0.8 ../../third_party/flann/lib/libflann_cpp_s.a -Wl,-rpath,/home/lovric_g/Applications/openMVG_Build/Linux-x86_64-Release:/home/lovric_g/Applications/anaconda2/lib
```

**Comment by pmoulon** [comment]
Have you tried to add -lgfortran?

**Comment by gnudo** [comment]
Thanks, Pierre! That fixes the problem. Now, I just see it has to be added many times during the build (of different components). Do you see a fast way of adding it to the cmake configs?

**Comment by pmoulon** [comment]
Here gfortran is required since Ceres has detected that you have lapack and blas.
So if you use classic cmake files and make it should work.
So the place to add it would be somewhere here:
https://github.com/openMVG/openMVG/blob/master/src/third_party/ceres-solver/CMakeLists.txt

**Comment by gnudo** [comment]
Thanks for the hint. I'll check that and maybe try do get back with some more general fix.

**Comment by gnudo** [comment]
After some more testing etc., the problem can be fixed (i.e. compilation works out of the box) by adding
```
LIST(APPEND CERES_LIBRARY_PRIVATE_DEPENDENCIES gfortran)
```
to the following line in [https://github.com/openMVG/openMVG/blob/master/src/third_party/ceres-solver/internal/ceres/CMakeLists.txt](https://github.com/openMVG/openMVG/blob/master/src/third_party/ceres-solver/internal/ceres/CMakeLists.txt#L157-L157) .
Obviously, not being directly related to openMVG, I wonder why this problem doesn't occur on other systems. So, I actually have to clue how one would fix this (maybe by manipulating _FindLAPACK.cmake_ module?!)

**Comment by pmoulon** [comment]
The best place to ask would be the ceres-solver mailing list ;-)
https://github.com/ceres-solver/ceres-solver
Can I close the thread since we have found a solution?

**Comment by gnudo** [comment]
sure :) thx for the help once again

**Comment by pmoulon** [comment]
You're welcome. Happy to answer questions, since it shows that there is users ;-)
