### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by changchuming** [openMVG/openMVG#593]
I'm trying to build on an Ubuntu 14.04.3 LTS and I keep getting this error when compiling openMVG2openMVS.cpp. There is a redefinition error within InterfaceMVS.h but I don't think there's actually a repeat.

> In file included from /root/openMVG/src/software/SfM/main_openMVG2openMVS.cpp:13:0:
> /root/openMVG/src/software/SfM/InterfaceMVS.h:139:6: error: redefinition of ‘bool ARCHIVE::Save(ARCHIVE::ArchiveSave&, const _Tp&) [with _Tp = unsigned int]’
>  bool Save<TYPE>(ArchiveSave& a, const TYPE& v) { \
>       ^
> /root/openMVG/src/software/SfM/InterfaceMVS.h:152:1: note: in expansion of macro ‘ARCHIVE_DEFINE_TYPE’
>  ARCHIVE_DEFINE_TYPE(size_t)
>  ^
> /root/openMVG/src/software/SfM/InterfaceMVS.h:139:6: error: ‘bool ARCHIVE::Save(ARCHIVE::ArchiveSave&, const _Tp&) [with _Tp = unsigned int]’ previously declared here
>  bool Save<TYPE>(ArchiveSave& a, const TYPE& v) { \
>       ^
> /root/openMVG/src/software/SfM/InterfaceMVS.h:151:1: note: in expansion of macro ‘ARCHIVE_DEFINE_TYPE’
>  ARCHIVE_DEFINE_TYPE(uint32_t)
>  ^

Any idea how to solve this?

**Comment by pmoulon** [comment]
Can you tell if you are using a 32 or 64 bit system?
BTW, if you don't need this binary, you can desactivate it in the software/sfm/CMakeLists.txt

**Comment by changchuming** [comment]
Hi, thanks for the prompt reply.
First of all, I want to thank you for all the work you've done in this area, it's amazing.
I'm using a 32-bit Linux machine hosted on DigitalOcean. We're trying to create a web app which reconstruct 3D models from pictures. It currently uses Bundler for reconstruction purposes.
I think I'll need that particular binary, as we're planning to test surface reconstruction with OpenMVS.

**Comment by pmoulon** [comment]
Your compilation problem is fixed in the develop branch.
See here for the fix: https://github.com/openMVG/openMVG/commit/9963a66bae826f014482f778d9cfa31bbd0e444a
I'm sure you will like OpenMVG, since it allow to parametrize the feature extraction & matching & sfm in a more easy way than Bundler.

Don't hesitate to ask question regarding the usage ;-)

**Comment by changchuming** [comment]
I recompiled with the develop branch and it works! Thanks for the help :)

**Comment by pmoulon** [comment]
Can I close the issue, or do you think you will need a Q&A here about some parameters... of the SfM toolchain?

**Comment by changchuming** [comment]
I'll ask again if I have any issues, I'll close this, thanks!
